### PR TITLE
Updating authors to reflect JHUGen additions

### PR DESCRIPTION
**Pull request by MohitS704**
[JHUGen Reference](https://github.com/JHUGen/JHUGen/pull/200)

### CODE REVIEW

**Review by michael11892 — APPROVED** [review]

**Review by usarica — CHANGES_REQUESTED** [review]
Same set of changes as in JHUGen PR https://github.com/JHUGen/JHUGen/pull/200 are needed to approve this PR.

**Review by gritsan — APPROVED** [review]
I believe we have resolved this issue.

**Comment by usarica** [comment]
> I believe we have resolved this issue.

I sent an email response on Nov. 15 at 7.09 am PT. In relation to that response, the links https://github.com/JHUGen/JHUGen/graphs/contributors and https://github.com/JHUGen/JHUGenMELA/graphs/contributors could be viewed to see the current lists of people who are visible as having contributed to code development.

**Review by usarica — CHANGES_REQUESTED** [review]
Once PR #40 is merged, there is one more change needed.

I see in the list of contributors to JHUGenMELA that Mostafa Mahdavikhorrami, formerly in ULB, has also contributed. His level of contribution was similar to Lucas's, so his name should also be added to the list of contributors.

**Comment by gritsan** [comment]
Git is a wrong place to discuss this, as stated earlier already:

> Once PR #40 is merged, there is one more change needed.
> 
> I see in the list of contributors to JHUGenMELA that Mostafa Mahdavikhorrami, formerly in ULB, has also contributed. His level of contribution was similar to Lucas's, so his name should also be added to the list of contributors.

**Comment by MohitS704** [comment]
Can we push this through then?

**Review by usarica — APPROVED** [review]

**Pull request merged**
