### PR TITLE
code owners

### PR DESCRIPTION
**Pull request by hroskes**

### CODE REVIEW

**Review by usarica — APPROVED** [review]

**Review by usarica — CHANGES_REQUESTED** [review]
Revoking earlier approval:
- Github warns that the file contains errors. I don't understand why you would change to '/'.

**Comment by usarica** [comment]
> Revoking earlier approval:
> 
> * Github warns that the file contains errors. I don't understand why you would change to '/'.

Another thing I do not understand:
Code owners do not need to be changed in order to add Jeff (or Andrei) to allow PR approvals. There is a MELADevs team under Setting/Collaborators and teams with a maintenance access permission. To my understanding, this should allow PR approvals for the members of this team (Jeff and Andrei are members). I would start from there to see whether modifying this permission structure makes the difference.

**Review by gritsan — APPROVED** [review]

**Comment by hroskes** [comment]
There is a box checked that requires at least one review from a code owner.  I fixed the syntax.

**Review by gritsan — APPROVED** [review]

**Comment by usarica** [comment]
It looks like the approval issue in #20 is resolved, so I will close this PR for now. If a separate discussion happens regarding the CODEOWNERS file, we can reopen it as long as you don't remove the branch.

**Comment by gritsan** [comment]
Lets reopen this PR and have it finished, since the effort was put into this, and it is in the right direction. @usarica: can you reopen and move it forward?

**Comment by gritsan** [comment]
It has been 9 days, any progress on this?

**Comment by usarica** [comment]
@gritsan This requires offline discussion and agreement. There is a reason why the CODEOWNERS file is implemented, and since the issue of Jeff's approval of PRs was not related to this file (as we have seen explicitly that he is able to approve and merge the previous PR), I do not think this PR is warranted.

**Comment by gritsan** [comment]
Please organize the offline discussion (2 people is enough) then

**Pull request closed without merging**
