### PR TITLE
Added Anomalous Zff Couplings Interface to JHUGen & MCFM (C)

### PR DESCRIPTION
**Pull request by michael11892**
Added an interface that enables parsing anomalous Zff couplings to MCFM through MELA. The current PR only includes the necessary C infrastructure and does _not_ explicitly update the python Mela() object. All python updates relevant to the interface are scheduled for a separate PR.

### CODE REVIEW

**Review by usarica — CHANGES_REQUESTED** [review]
As I mentioned previously in the JHUGenerator commit, I do not think the anomalous Zff couplings approach is a good way to move forward. For that reason, I do not think it is a good idea to propagate it to MELA. Besides, the current architecture in MELA has been growing obsolete, so adding more 'functionalities' is not the best course of action at this moment. More discussion is necessary before we can move forward. If you need it for private studies, you can certainly use a private modification in your setup, but I would oppose making public releases.

**Review by michael11892 — COMMENTED** [review]
Fixed merge conflict due to interim fix

**Comment by gritsan** [comment]
We can have more discussion, but the outcome will not change: The generator options and the MELA option must match, because the users must be able to re-weight the generated samples, and to calculate discriminants. So, this discussion must focus on implementation, not on the idea of having this option, which has already been accepted to move forward. This is in reply to this comment:

> As I mentioned previously in the JHUGenerator commit, I do not think the anomalous Zff couplings approach is a good way to move forward. For that reason, I do not think it is a good idea to propagate it to MELA. Besides, the current architecture in MELA has been growing obsolete, so adding more 'functionalities' is not the best course of action at this moment. More discussion is necessary before we can move forward. If you need it for private studies, you can certainly use a private modification in your setup, but I would oppose making public releases.

**Comment by usarica** [comment]
> We can have more discussion, but the outcome will not change: The generator options and the MELA option must match, because the users must be able to re-weight the generated samples, and to calculate discriminants. So, this discussion must focus on implementation, not on the idea of having this option, which has already been accepted to move forward. This is in reply to this comment:
> 
> > As I mentioned previously in the JHUGenerator commit, I do not think the anomalous Zff couplings approach is a good way to move forward. For that reason, I do not think it is a good idea to propagate it to MELA. Besides, the current architecture in MELA has been growing obsolete, so adding more 'functionalities' is not the best course of action at this moment. More discussion is necessary before we can move forward. If you need it for private studies, you can certainly use a private modification in your setup, but I would oppose making public releases.

I would suggest to move planning discussions offline. If the intention is for reweighting and discriminants to be computed, MELA is not the only place modifications should be made, and such discussion has larger scope and implications than what this PR attempts to address.

**Comment by michael11892** [comment]
I have ran testME_all.py and testME_more.py with no errors returned for any test case. I have also tested the AZff couplings with the addition of ghzgs2=1 and checked the kinematic distributions to make sure that they matched the non-AZff results (to good approximation, the exact kinematic variables do have a subtle dependence on AZff) and the resulting distributions match our expectations, meaning that no bugs have been introduced into the code for independent ME calculations.

@usarica, you mentioned some cosmetic changes which you wanted to make. Given that the tests you provided are now concluded, it would be a good idea to tackle those changes before the final merge.

**Review by gritsan — APPROVED** [review]

**Review by gritsan — CHANGES_REQUESTED** [review]
We really need to proceed with this interface, experts are waiting. Therefore:
Ulascan: please communicate your proposed cosmetic changes without so much delay. 
Michalis: please include updates to JHUGen matrix element interface to this PR, since it relies on the same changes as for MCFM. We cannot wait much longer for sequential updates.

**Review by gritsan — APPROVED** [review]

**Review by usarica — APPROVED** [review]
This is to close on this PR though #29 should be the one to approve.

**Comment by michael11892** [comment]
Let's do things in an orderly fashion. Let's merge #28 and then #29.

**Review by gritsan — APPROVED** [review]

**Pull request merged**
