### PR TITLE
Enable deleting created symbolic links

### PR DESCRIPTION
**Pull request by mostafa1993**

### CODE REVIEW

**Comment by usarica** [comment]
@mostafa1993 Thanks for the PR. Putting the rm statement in the destructor is not necessarily an ideal one. Consider the scenario where there are more than one Mela objects, each one being deleted separately. Then deletion of one object could disrupt the operation of the other objects. My suggestion would be to move these statements to a static function (static void Mela::cleanLinkedFiles()). Then the user can call it in the destructor of their event looper.

**Comment by mostafa1993** [comment]
> @mostafa1993 Thanks for the PR. Putting the rm statement in the destructor is not necessarily an ideal one. Consider the scenario where there are more than one Mela objects, each one being deleted separately. Then deletion of one object could disrupt the operation of the other objects. My suggestion would be to move these statements to a static function (static void Mela::cleanLinkedFiles()). Then the user can call it in the destructor of their event looper.

Done :)

**Comment by usarica** [comment]
@mostafa1993 Thanks for making the change quickly.

@TOPAZdevelop @gritsan @hroskes Would someone please approve the PR? It adds a clean-up functionality without disrupting core functions.

**Review by usarica — APPROVED** [review]

**Review by usarica — APPROVED** [review]
The added changes are necessary for JHUGenMELA to function in later versions of HTCondor and glidein migrations. They need to be approved for JHUGenMELA to function on remote machines.

**Review by TOPAZdevelop — APPROVED** [review]

**Pull request merged**
