### PR TITLE
Updating ResonancePropagatorScheme and Adding new gcc10 compiled MCFM library

### PR DESCRIPTION
**Pull request by lk11235**
Added the AltRunningWidth=4 to match previously accepted changes made to ResonancePropagatorScheme

### CODE REVIEW

**Review by usarica — APPROVED** [review]

**Comment by lk11235** [comment]
Pushed edits to the master branch without realizing that this PR was still open. But keeping these commits included here since they are also small necessary changes which were explicitly requested. 

Added a new download.url file and condition in the setup script to use the recently compiled and uploaded gcc10 MCFM library.

**Comment by lk11235** [comment]
Sorry for the delay in commenting. JHUGen will compile and run with MELA using the gcc920 library.

**Comment by usarica** [comment]
Great! So in that case, do we still need this PR, given that the MCFM library compiled under gcc 9.2.0 works in gcc 10?

**Comment by jdavis36** [comment]
Hi All,

Just to add my two cents. I think the issue isn't so much that the we need an explicit gcc 10 version.  The issue is that if you run the setup script on gcc10, all of the MELA libraries would go into the gcc10 folder and the mcfm library goes into the gcc920 folder. So then when you export the library paths using 

`./setup env`

LD_LIBRARY_PATH does not have the path to the mcfm library. This is an easy fix for a developer, but for an end user its not immediately apparent that the mcfm library was dumped into a different directory. 

Could we change the steup.sh to put whatever mcfm library we use in the correct place, or make sure the environment setup script also includes the correct export path?

**Comment by lk11235** [comment]
Yes, this is the obvious fix and one that has already been implemented in our privately compiled version of JHUGen for gridpack production. I will update this PR with the relevant changes and remove the unnecessary gcc10 library once I'm back on a computer.

**Comment by usarica** [comment]
@jdavis36 @lk11235 I think the best solution is to remove these lines altogether: https://github.com/JHUGen/JHUGenMELA/blob/master/MELA/setup.sh#L56-L58. That way, SCRAM_ARCH will never be referenced anywhere in the JHUGen framework. (Do we accidentally use this environment variable in the Lexicon?)

**Comment by gritsan** [comment]
Please close on this PR, we need to move forward

**Comment by usarica** [comment]
> Please close on this PR, we need to move forward

Waiting for @lk11235 to take the requested action above.

**Comment by lk11235** [comment]
Making the aforementioned edits and will be testing the full JHUGen compilation from scratch

**Comment by lk11235** [comment]
MELA compilation has been tested and works with the requested changes. This PR should be good to merge now

**Review by gritsan — APPROVED** [review]

**Comment by gritsan** [comment]
We need to release a new version of the generator ASAP before the holidays. This is needed by the BPH group on CMS, with changes introduced by Mohit. Could everybody please make an effort to close the loop?

**Comment by usarica** [comment]
@gritsan This PR is fine, but there are still things to fix in Mohit's PR.

**Review by usarica — APPROVED** [review]

**Pull request merged**
