### PR TITLE
Modifications to PR #28

### PR DESCRIPTION
**Pull request by usarica**
Style modifications to to PR #28

### CODE REVIEW

**Comment by usarica** [comment]
Merging this PR will automatically merge #28. @gritsan @hroskes @jdavis36 please kindly approve and merge.

**Comment by usarica** [comment]
Last commit also addresses the bug reported in Issue #24.

**Review by michael11892 — APPROVED** [review]
Cosmetic changes have been reviewed and all appears well from my end. I approve this PR.

**Review by gritsan — DISMISSED** [review]

**Comment by usarica** [comment]
This is why I suggested to merge #29 directly. Now everyone has to reapprove.

**Review by gritsan — APPROVED** [review]

**Comment by usarica** [comment]
MCFM version seems not to have been incremented in #28. The library should be recompiled for directory on the web corresponding to major gfortran changes, and the new libmcfm_708.so files need to be uploaded before a PR to the JHUGenerator repository is made or the changes are announced. This happens externally, so it does not affect the approval of this PR (though two people still need to reapprove one last time).

**Review by gritsan — DISMISSED** [review]

**Review by michael11892 — APPROVED** [review]

**Comment by michael11892** [comment]
Are we certain that the PR merge-base was changed? It is not reflected during code review.

**Review by gritsan — DISMISSED** [review]
Why are we going in circles on this PR? Could this be done in a more straightforward way?

**Comment by usarica** [comment]
I don't know why it goes in circles - I am definitely not the one dismissing approvals.

I am using some dark magic to merge this PR given that two people already agree on the changes.

**Pull request merged**
